import "@/styles/styles.scss"

import "@/images/favicon32.png"
import "@/images/plant.jpg"
import "@/images/plant-bonsai.jpg"
import "@/images/plant-preserved.jpg"
import "@/images/plant-edible.jpg"
import "@/images/exp-online.jpg"
import "@/images/exp-subsc.jpg"
import "@/images/exp-gift.jpg"
import "@/images/item-a101.jpg"
import "@/images/item-ea201.jpg"
import "@/images/item-flower.jpg"
import "@/images/item-b100.jpg"

