import "@/styles/style.scss"

import "@/images/favicon32.png"
import "@/images/eyecatch.jpg"
import "@/images/workspace.jpg"
import "@/images/workspace-front.jpg"
import "@/images/wall.jpg"
import "@/images/plan.jpg"
import "@/images/idea.png"
import "@/images/business.png"
import "@/images/secure.png"
